export const ActionTypes = {
  GET_PRODUCT_BY_SELLER_ID: 'GET_PRODUCT_BY_SELLER_ID',
  GET_PRODUCT_BY_SEARCH: 'GET_PRODUCT_BY_SEARCH',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED',
  SET_ERROR: 'SET_ERROR',
  SET_LOADING: 'SET_LOADING',
};
